frameworkVersion: "3"

service: registeration-service

plugins:
  - serverless-better-credentials
  - serverless-webpack
  - serverless-offline

package:  
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  stackName: registeration-stack
  region: us-east-1
  memorySize: 128
  timeout: 15
  logRetentionInDays: 60
  versionFunctions: false

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
            - ec2:DescribeSecurityGroups
            - ec2:DescribeSubnets
            - ec2:DescribeVpcs
            - ssm:DescribeParameters
            - ssm:GetParameters
            - ssm:GetParameter
            - ssm:GetParametersByPath
            - ssm:PutParameter
          Resource: "*"
        - Effect: "Allow"
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: 
            - "arn:aws:s3:::${file(config.json):S3_BUCKET_NAME}/*" 
functions:
  test:
    name: test
    handler: src/connectors/lambda-functions/test/index.handler
    events:
      - http:
          path: test
          method: get
          cors: true

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    packager: 'npm'
    includeModules: true